config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('master/', include('master.urls')),
    path('plan/', include('plan.urls')),
    path('sample/', include('sample.urls')),
]

plan/urls.py
from django.urls import path, include
from plan import views

app_name = 'plan'
urlpatterns = [
    path('date/<str:target_date>/category/<int:target_category>/id/<int:target_id>/', views.PlanView.plan_edit, name='plan_edit'),
]

sample/urls.py
from django.urls import path
from sample import views

app_name = 'sample'
urlpatterns = [
    path('parent/', views.ParentListView.as_view(), name='parent_list'),
    path('parent/add/', views.ParentView.parent_edit, name='parent_add'),
    path('parent/put/<int:parent_id>/', views.ParentView.parent_edit, name='parent_put'),
    path('parent/del/<int:parent_id>/', views.ParentView.parent_del, name='parent_del'),
    path('child/<int:parent_id>/', views.ChildListView.as_view(), name='child_list'),
    path('navigation/', views.NavigationView.as_view(), name='navigation'),
    path('navigation2/', views.NavigationView2.as_view(), name='navigation2'),
]

sample/forms.py
from django.forms import ModelForm
from sample.models import Parent, Child


class ParentForm(ModelForm):
    class Meta:
        model = Parent
        fields = ('name', )
       
class ChildForm(ModelForm):
    class Meta:
        model = Child
        fields = ('name', ) 

sample/views.py
import json

from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.views import View
from django.views.generic.list import ListView
from django.views.generic import RedirectView

from sample.models import Parent
from sample.forms import ParentForm


class ParentListView(ListView):
    template_name='sample/parent_list.html'
    context_object_name='parents'
    paginate_by = 2

    def get(self, request, *args, **kwargs):
        """親一覧"""
        parents = Parent.objects.all().order_by('id')
        self.object_list =parents
        context = self.get_context_data(object_list=self.object_list)
        return self.render_to_response(context)

class ParentView(View):
    def parent_edit(request, parent_id=None):
        """親編集"""
        if parent_id:
            parent = get_object_or_404(Parent, pk=parent_id)
        else:
            parent = Parent()

        if request.method == 'POST':
            form = ParentForm(request.POST, instance=parent)
            if form.is_valid():
                parent = form.save(commit=False)
                parent.save()
                return redirect('sample:parent_list')
        else:
            form = ParentForm(instance=parent)

        return render(request, 'sample/parent_edit.html', dict(form=form, parent_id=parent_id))
    
    def parent_del(request, parent_id):
        """親削除"""
        parent = get_object_or_404(Parent, pk=parent_id)
        parent.delete()
        return redirect('sample:parent_list')


class ChildListView(ListView):
    """子一覧"""
    template_name='sample/child_list.html'
    context_object_name='children'
    paginate_by = 2

    def get(self, request, *args, **kwargs):
        parent = get_object_or_404(Parent, pk=kwargs['parent_id'])
        children = parent.children.all().order_by('id')
        self.object_list = children
        context = self.get_context_data(object_list=self.object_list, parent=parent)
        return self.render_to_response(context)


class NavigationView(View):
    """ナビゲーション"""
    template_name='sample/navigation.html'

    def get(self, request, *args, **kwargs):
        navigation = [];
        
        parents = Parent.objects.all().order_by('id')
        for parent in parents:
            parent_node = dict();
            parent_node['text'] = parent.name
            parent_node['nodes'] = []
            navigation.append(parent_node)

            children = parent.children.all().order_by('id')
            for child in children:
                child_node = dict();
                child_node['text'] = child.name
                child_node['nodes'] = []
                parent_node['nodes'].append(child_node)
        return render(request, self.template_name, {'navigation': json.dumps(navigation)})
        

class NavigationView2(View):
    """ナビゲーション"""
    template_name='sample/navigation2.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

templates/sample/child_list.html
{% extends "base.html" %}

{% block title %}子一覧{% endblock title %}

{% block content %}
<h4 class="mt-4 border-bottom">子一覧</h4>

<h5 class="mt-2 border-bottom">
    <a href="{% url 'sample:parent_list' %}">
        <small>{{ parent.name }}</small>
    </a>
</h5>
<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">名称</th>
        </tr>
    </thead>
    <tbody>
        {% for child in children %}
        <tr>
            <th scope="row">{{ child.id }}</th>
            <td>{{ child.name }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

templates/sample/navigation.html
{% extends "base.html" %}

{% block title %}ナビゲーション{% endblock title %}

{% block content %}
<h4 class="mt-4 border-bottom">ナビゲーション</h4>

<p>
	<h6 class="mt-3 border-bottom">bootstrap-treeview</h6>
	<div style="float: right" id="select_node1"></div><br>
	<div id="navigation"></div>
</p>

<p>
	<h6 class="mt-3 border-bottom">vuetify Treeview</h6>
	<div style="float: right" id="select_node2"><font color="red">初回選択でイベントが発行されないのはなぜ?</font></div><br>
	<div id="navigation2" style="height: 288px;">
		<v-app id="inspire">
		  <v-treeview
		  mandatory
			activatable
			:items="items"
			:return-object="true"
			@click="piyo"
			@input="onInputed"
			@update:active="onSelected"
			@update:open="onOpened"
		  ></v-treeview>
		</v-app>
	</div>
</p>

<p>
	<h6 class="mt-3 border-bottom">vuetify Lists</h6>
	<!-- https://v2.vuetifyjs.com/ja/components/list-item-groups/#usage -->
	<!-- https://v2.vuetifyjs.com/ja/components/lists/ -->
	<!-- https://qiita.com/rubytomato@github/items/784a0eb013a9de1937bd -->
	<div id="navigation3" style="height: 352px;width: 400px;">
		<v-app id="inspire">
			<v-card
				class="mx-auto"
				width="400"
			>
				<v-list expand>
					<v-subheader>ナビゲーション</v-subheader>
					<v-list-group v-for="item in items" :key="item.text" no-action>
						<template v-slot:activator>
							<v-list-item-content>
								<v-list-item-title v-text="item.text"></v-list-item-title>
							</v-list-item-content>
						</template>
						<template v-for="node in item.nodes">
							<v-list-item :key="node.text" link>
								<v-list-item-content>
									<v-list-item-title v-text="node.text"></v-list-item-title>
								</v-list-item-content>
							</v-list-item>
						</template>
					</v-list-group>
				</v-list>
			</v-card>
		</v-app>
	</div>
</p>
<div style="float: right"></p><a href="{% url 'sample:parent_list' %}">親一覧へ</a></div>
{% endblock content %}

{% block extra_js %}
<script>
	var navigationData = JSON.parse('{{ navigation | safe }}');
    $('#navigation').treeview({
		data: navigationData,
		onNodeSelected: function(event, node) {
			document.getElementById('select_node1').innerHTML = node.text + ' が選択されました。';
		}
	});
	$('#navigation').on('nodeUnselected', function(event, node) {
			document.getElementById('select_node1').innerHTML = '選択が解除されました。';
		});
	$('#navigation').treeview('selectNode', [ 0 ]);
	$('#navigation').treeview('revealNode', 0);
</script>
<script>
	var navigationData2 = [];
	var index = 0;
	JSON.parse('{{ navigation | safe }}').forEach(function(parent){
		index++;
		var node = { id: index, name: parent.text, children: []};
		parent.nodes.forEach(function(child){
			index++;
			node.children.push({ id: index, name: child.text, children: []});
		});
		navigationData2.push(node);
	});

	var tree = new Vue({
		el: '#navigation2',
		vuetify: new Vuetify(),
		data: () => ({
			items: navigationData2,
		}),
        methods: {
			onInputed: function(nodes) {
				var index2 = 0;
        	},
			onSelected: function(nodes) {
				if(nodes.length){
      				document.getElementById('select_node2').innerHTML = nodes[0].name + ' が選択されました。';
				} else {
      				document.getElementById('select_node2').innerHTML = '選択が解除されました。';
				}
        	},
			onOpened: function(nodes) {

        	},
		},
	})
</script>
<script>
	var navigationData3 = JSON.parse('{{ navigation | safe }}');
	var list = new Vue({
		el: '#navigation3',
		vuetify: new Vuetify(),
		data: () => ({
			items: navigationData3,
			model: 0,
		}),
	})
</script>
{% endblock %}

templates/sample/navigation2.html
{% extends "base.html" %}

{% block title %}ナビゲーション{% endblock title %}

{% block content %}
<div id="navigation">
	<div style="float: right" id="select_node"></div>
    <my-navigation v-on:node-click="select"></my-navigation>
</div>
{% endblock content %}

{% block extra_js %}
{% load static %}
<script type="module" src="{% static 'customjs\navigation.js' %}"></script>
{% endblock %}

templates/sample/parent_edit.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block title %}親編集{% endblock title %}

{% block content %}
    <h4 class="mt-4 mb-5 border-bottom">親編集</h4>
    {% if parent_id %}
    <form action="{% url 'sample:parent_put' parent_id=parent_id %}" method="post">
    {% else %}
    <form action="{% url 'sample:parent_add' %}" method="post">
    {% endif %}
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    <div class="form-group row">
        <div class="offset-md-3 col-md-9">
          <button type="submit" class="btn btn-primary">送信</button>
        </div>
    </div>
    </form>
    <a href="{% url 'sample:parent_list' %}" class="btn btn-secondary btn-sm">戻る</a>
{% endblock content %}

templates/sample/parent_list.html
{% extends "base.html" %}

{% block title %}親一覧{% endblock title %}

{% block content %}
<h4 class="mt-4 border-bottom">親一覧</h4>
<a href="{% url 'sample:parent_add' %}" class="btn btn-primary btn-sm my-3">追加</a>
<table class="table table-striped table-bordered">
	<thead>
		<tr>
			<th scope="col">ID</th>
			<th scope="col">名称</th>
			<th scope="col">操作</th>
		</tr>
	</thead>
	<tbody>
		{% for parent in parents %}
		<tr>
			<th scope="row">{{ parent.id }}</th>
			<td>{{ parent.name }}</td>
			<td>
				<a href="{% url 'sample:parent_put' parent_id=parent.id %}" class="btn btn-outline-primary btn-sm">編集</a>
				<a href="{% url 'sample:parent_del' parent_id=parent.id %}" class="btn btn-outline-danger btn-sm">削除</a>
				<a href="{% url 'sample:child_list' parent_id=parent.id %}" class="btn btn-outline-info btn-sm">BG一覧</a>
			</td>
		</tr>
		{% endfor %}
	</tbody>
</table>

{% if is_paginated %}
<nav aria-label="Page navigation">
	<ul class="pagination">
	{% if page_obj.has_previous %}
		<li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous"><span aria-hidden="true">&laquo;</span><span class="sr-only">前</span></a></li>
	{% else %}
		<li class="page-item disabled"><a class="page-link" href="#" aria-label="Previous"><span aria-hidden="true">&laquo;</span><span class="sr-only">前</span></a></li>
	{% endif %}
	{% for linkpage in page_obj.paginator.page_range %}
		{% ifequal linkpage page_obj.number %}
		<li class="page-item active"><a class="page-link" href="#">{{ linkpage }}</a></li>
		{% else %}
		<li class="page-item"><a class="page-link" href="?page={{ linkpage }}">{{ linkpage }}</a></li>
	{% endifequal %}
	{% endfor %}
	{% if page_obj.has_next %}
		<li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next"><span aria-hidden="true">&raquo;</span><span class="sr-only">次</span></a></li>
	{% else %}
		<li class="page-item disabled"><a class="page-link" href="#" aria-label="Next"><span aria-hidden="true">&raquo;</span><span class="sr-only">次</span></a></li>
	{% endif %}
	</ul>
</nav>
{% endif %}
<div style="float: right"></p><a href="{% url 'sample:navigation' %}">ナビゲーションへ</a></div>
{% endblock content %}