config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('master/', include('master.urls')),
    path('plan/', include('plan.urls')),
    path('sample/', include('sample.urls')),
]

master/parent/urls.py
from django.urls import path, include
from master.parent import views

app_name = 'parent'
urlpatterns = [
    path('', views.ParentView.as_view(), name='parent_list'),
    path('<int:target_id>', views.ParentView.parent_edit, name='parent_list_by_id'),
    path('put/<int:target_id>/', views.ParentView.parent_edit, name='parent_put'),
    # path('parent/', views.ParentListView.as_view(), name='parent_list'),
    # path('parent/add/', views.ParentView.parent_edit, name='parent_add'),
    # path('parent/del/<int:parent_id>/', views.ParentView.parent_del, name='parent_del'),
    # path('child/<int:parent_id>/', views.ChildListView.as_view(), name='child_list'),
    # path('navigation/', views.NavigationView.as_view(), name='navigation'),
]

master/urls.py
from django.urls import path, include
from master import views

app_name = 'master'
urlpatterns = [
    # path("parent/", include('master.parent.urls'), name="parent"),
    path('', views.master, name='master'),
    path('parent/', views.ParentView.parent_edit, name='parent_list'),
    path('parent/<int:target_id>/', views.ParentView.parent_edit, name='parent_list_by_id'),
    path('parent/put/', views.ParentView.parent_edit, name='parent_put'),
    path('parent/put/<int:target_id>/', views.ParentView.parent_edit, name='parent_put'),
    path('parent/new/', views.ParentView.parent_edit, name='parent_new'),
    path('parent/add/', views.ParentView.parent_edit, name='parent_add'),
    path('parent/del/<int:target_id>/', views.ParentView.parent_del, name='parent_del'),
]

plan/urls.py
from django.urls import path, include
from plan import views

app_name = 'plan'
urlpatterns = [
    path('date/<str:target_date>/category/<int:target_category>/id/<int:target_id>/', views.PlanView.plan_edit, name='plan_edit'),
]

sample/urls.py
from django.urls import path
from sample import views

app_name = 'sample'
urlpatterns = [
    path('parent/', views.ParentListView.as_view(), name='parent_list'),
    path('parent/add/', views.ParentView.parent_edit, name='parent_add'),
    path('parent/put/<int:parent_id>/', views.ParentView.parent_edit, name='parent_put'),
    path('parent/del/<int:parent_id>/', views.ParentView.parent_del, name='parent_del'),
    path('child/<int:parent_id>/', views.ChildListView.as_view(), name='child_list'),
    path('navigation/', views.NavigationView.as_view(), name='navigation'),
    path('navigation2/', views.NavigationView2.as_view(), name='navigation2'),
]

master/models.py
from django.db import models


class Parent(models.Model):
    """親"""
    name = models.CharField('名称', max_length=255)

    def __str__(self):
        return self.name


class Child(models.Model):
    """子"""
    name = models.CharField('名称', max_length=255)
    parent =  models.ForeignKey(Parent, verbose_name='名称', related_name='children', on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name

master/parent/models.py
from django.db import models

# Create your models here.

master/forms.py
from django.forms import ModelForm
from master.models import Parent, Child


class ParentForm(ModelForm):
    class Meta:
        model = Parent
        fields = ('name', )
       
class ChildForm(ModelForm):
    class Meta:
        model = Child
        fields = ('name', ) 

master/parent/forms.py
from django.forms import ModelForm
from sample.models import Parent, Child


class ParentForm(ModelForm):
    class Meta:
        model = Parent
        fields = ('name', )

master/parent/views.py
import json

from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.views import View
from django.views.generic.list import ListView

from master.models import Parent
from sample.forms import ParentForm


class ParentView(View):
    template_name='master/parent/parent_list.html'
    paginate_by = 2 

    def parent_edit(request, target_id=None):
        parent_list = []
        target_index = -1
        index = 0

        # 親レコード全取得
        parents = Parent.objects.all().order_by('id')

        # 親リスト作成
        for parent in parents:
            parent_node = dict();
            parent_node['id'] = parent.id
            parent_node['text'] = parent.name
            parent_node['link'] = "./" + str(parent.id)
            parent_list.append(parent_node)

            # 選択指定対象のデータ
            if (parent.id == target_id):
                target_index = index
            else:
                index += 1

        if request.method == 'POST':
            if target_id:
                parent = get_object_or_404(Parent, pk=target_id)
            else:
                parent = Parent()

            form = ParentForm(request.POST, instance=parent)

            if form.is_valid():
                parent = form.save(commit=False)
                parent.save()
                if target_id:
                    return redirect('master.parent:parent_list')
                    # return redirect('sample:parent_list')
                    # return redirect('parent:parent_list_by_id', target_id = target_id)
                else:
                    return redirect('master.parent:parent_list')
        
        form = ParentForm(instance=parents[target_index])
        return render(request, 'master/parent/parent_list.html', dict(
            parent_list = json.dumps(parent_list),
            target_index = target_index,
            target_id = target_id,
            form = form
        ))

master/views.py
import json

from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.views import View
from django.views.generic.list import ListView

from master.models import Parent
from master.forms import ParentForm


def master(request):
    return render(request, 'master/master_base.html')

class ParentView(View):
    def parent_edit(request, target_id=None):
        parent_list = []
        index = 0

        # 親レコード全取得
        parents = Parent.objects.all().order_by('id')

        # 親リスト作成
        for parent in parents:
            parent_node = dict();
            parent_node['id'] = parent.id
            parent_node['name'] = parent.name
            parent_node['link'] = "/master/parent/" + str(parent.id)
            parent_list.append(parent_node)

            # 編集対象のデータ
            if (parent.id == target_id):
                form = ParentForm(instance=parent)

        if request.method == 'POST':
            if target_id:
                parent = get_object_or_404(Parent, pk=target_id)
            else:
                parent = Parent()

            form = ParentForm(request.POST, instance=parent)

            if form.is_valid():
                parent = form.save(commit=False)
                parent.save()
                if target_id:
                    return redirect('master:parent_list_by_id', target_id = target_id)
                else:
                    return redirect('master:parent_list')
        
        if(target_id == None):
            form = ParentForm(instance=Parent())
        return render(request, 'master/parent_list.html', dict(
            parent_list = json.dumps(parent_list),
            target_id = target_id,
            form = form
        ))
        
    def parent_del(request, target_id):
        """親削除"""
        parent = get_object_or_404(Parent, pk=target_id)
        parent.delete()
        return redirect('master:parent_list')

templates/master/master_base.html
{% extends "base.html" %}

{% block title %}マスター管理{% endblock title %}

{% block content %}
<h1 class="mt-4 border-bottom">マスター管理</h1>
<div><h3><a href="{% url 'master:parent_list' %}">親一覧へ</a></h3></div>
{% endblock content %}

{% block extra_js %}
{% endblock %}

templates/master/parent_list.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block extra_css %}
<style>
	.master_list {
		clear: both;
	}
	.v-application--wrap {
		min-height: 259px;
		max-height: 259px;
		overflow-y: scroll;
	}
	.v-list-item-group .v-list-item--active {
   		color: #1976d2;
	}
	.master_editor {
		clear: both;
		width: 100%;
	}
</style>

{% endblock %}
{% block extra_vuejs_tmp %}{% endblock %}

{% block title %}親一覧{% endblock title %}

{% block content %}
<h4 class="mt-4 border-bottom">親一覧</h4>
<div style="float: right; display:inline;">
	<p ><a href="{% url 'sample:navigation' %}">ナビゲーションへ</a></p>
	<!-- https://vuetifyjs.com/ja/components/lists/ -->
	<!-- https://vuetifyjs.com/ja/api/v-list-item/ -->
	<!-- https://v2.vuetifyjs.com/ja/components/list-item-groups/#usage -->
	<!-- https://v2.vuetifyjs.com/ja/components/lists/ -->
	<!-- https://qiita.com/rubytomato@github/items/784a0eb013a9de1937bd -->
</div>
<div id="palent_list" class="master_list">
	<v-app id="inspire">
		<v-card
			class="mx-auto"
			width="100%"
		>
			<v-list>
				<v-list-item-group 
					v-model="model"
				>
					<v-list-item
						class="border"
						v-for="(item, i) in items"
						:color=success
						:key="i"
						:link=true
						:href="item.link"
					>
					<v-list-item-content >
						<v-list-item-title v-text="item.id"></v-list-item-title>
					</v-list-item-content>
					<v-list-item-content>
						<v-list-item-title v-text="item.name"></v-list-item-title>
					</v-list-item-content>
					</v-list-item>
				</v-list-item-group>
			</v-list>
		</v-card>
	</v-app>
</div>
<div style="float: right">
	<!-- https://v4.bootstrap-guide.com/components/buttons -->
	<!-- https://v4.bootstrap-guide.com/utilities/borders -->
	<a href="{% url 'master:parent_new' %}" class="btn btn-primary btn-sm my-3">新規</a>
	{% if target_id %}
	<a href="{% url 'master:parent_del' target_id=target_id %}" class="btn btn-danger btn-sm">削除</a>
	{% else %}
	<a class="btn btn-danger btn-sm disabled">削除</a>
	{% endif %}
</div>

<div  class="master_editor">
    {% if target_id %}
    <form action="{% url 'master:parent_put' target_id=target_id %}" method="post">
	{% else %}
	<form action="{% url 'master:parent_add' %}" method="post">
	{% endif %}
		{% csrf_token %}
		{% bootstrap_form form show_label=True layout='horizontal' %}
		<div class="form-group row">
			<div class="offset-md-3 col-md-9">
			<button type="submit" class="btn btn-outline-success" style="float: right">
				{% if target_id %}
				更新
				{% else %}
				登録
				{% endif %}
			</button>
			</div>
		</div>
	</form>
</div>
{% endblock content %}
{% block extra_js %}
<script>
	var parentsList = new Vue({
		el: '#palent_list',
		vuetify: new Vuetify(),
		data: () => ({
			items: JSON.parse('{{ parent_list | safe }}'),
			model: Number('{{ target_id }}'),
		})
	})
</script>
{% endblock %}